import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { PwaRegister } from "@/components/common/PwaRegister";
import { ThemeColorSync } from "@/components/common/ThemeColorSync";
import "./globals.css";

// Inter is what ChatGPT / Linear / Vercel / Stripe / most modern fintech
// dashboards use. Self-hosted via `next/font` so no extra request hits
// fonts.googleapis at runtime — the .woff2 ships from /_next/static and
// the font-display: swap behaviour comes free with the helper. The full
// 400/500/600/700 range covers every body / button / heading / numeric
// weight used across the app.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "MarginPlant Broker — Indian Trading Platform",
    template: "%s · MarginPlant Broker",
  },
  description:
    "Trade Indian stocks, F&O, commodities, currencies, and crypto with MarginPlant Broker — fast, transparent, dark-themed.",
  icons: { icon: "/icon.svg" },
  // PWA — Apple-specific bits (Android/Chrome pick these up from
  // /manifest.webmanifest auto-generated by app/manifest.ts).
  applicationName: "MarginPlant",
  appleWebApp: {
    capable: true,
    title: "MarginPlant",
    statusBarStyle: "black-translucent",
  },
  // Manifest path is auto-injected by Next when app/manifest.ts
  // exists; declaring it here is belt-and-braces for older crawlers.
  manifest: "/manifest.webmanifest",
  // Disable Chrome's "Translate page?" infobar — refreshing the app
  // kept surfacing the prompt on Hindi/regional-locale devices, and
  // the trading numbers MUST NOT be auto-translated (entry → "prawesh",
  // BUY/SELL → "kharidein/bechein") because the broker UI relies on
  // exact English labels for SOPs/screen-shares. The pair of <meta>s
  // is the canonical opt-out (Google + W3C).
  other: {
    google: "notranslate",
    "google-site-verification": "",
  },
};

export const viewport: Viewport = {
  // Match the OS chrome (Android status bar / Chrome address bar) to
  // the app's current theme instead of the brand emerald everywhere.
  // The two media-keyed entries let the BROWSER pick the right one
  // when there's no user-set theme; the <ThemeColorSync> client
  // component below overrides this in real time when the user flips
  // light/dark from Profile → Preferences so the top safe-area band
  // never stays green on a light-theme app screen.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  width: "device-width",
  initialScale: 1,
  // Lock pinch-zoom / double-tap-zoom on mobile so the installed PWA
  // (and the mobile browser view) feels like a native shell — user
  // spec: "zoom in zoom out mat ho". Desktop browsers ignore these,
  // accessibility users can still use Ctrl/Cmd-+/- which `userScalable`
  // doesn't block.
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // `translate="no"` on <html> is the canonical W3C signal to all
  // translation engines (Chrome, Edge, Safari, third-party widgets)
  // that the page must not be auto-translated. Combined with the
  // <meta name="google" content="notranslate" /> in metadata.other,
  // it prevents the "Translate page?" popup from showing on refresh
  // — important because mistranslated trading labels (BUY → kharidein)
  // would be unsafe.
  return (
    <html lang="en" translate="no" suppressHydrationWarning className={inter.variable}>
      <body className="font-sans antialiased">
        <PwaRegister />
        <ThemeColorSync />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
