import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { PwaRegister } from "@/components/common/PwaRegister";
import "./globals.css";

// Inter is what ChatGPT / Linear / Vercel / Stripe / most modern fintech
// dashboards use. Self-hosted via `next/font` so no extra request hits
// fonts.googleapis at runtime — the .woff2 ships from /_next/static and
// the font-display: swap behaviour comes free with the helper. The full
// 400/500/600/700 range covers every body / button / heading / numeric
// weight used across the app.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "MarginPlant Broker — Indian Trading Platform",
    template: "%s · MarginPlant Broker",
  },
  description:
    "Trade Indian stocks, F&O, commodities, currencies, and crypto with MarginPlant Broker — fast, transparent, dark-themed.",
  icons: { icon: "/icon.svg" },
  // PWA — Apple-specific bits (Android/Chrome pick these up from
  // /manifest.webmanifest auto-generated by app/manifest.ts).
  applicationName: "MarginPlant",
  appleWebApp: {
    capable: true,
    title: "MarginPlant",
    statusBarStyle: "black-translucent",
  },
  // Manifest path is auto-injected by Next when app/manifest.ts
  // exists; declaring it here is belt-and-braces for older crawlers.
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  themeColor: "#10b981",
  width: "device-width",
  initialScale: 1,
  // Lock pinch-zoom / double-tap-zoom on mobile so the installed PWA
  // (and the mobile browser view) feels like a native shell — user
  // spec: "zoom in zoom out mat ho". Desktop browsers ignore these,
  // accessibility users can still use Ctrl/Cmd-+/- which `userScalable`
  // doesn't block.
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className="font-sans antialiased">
        <PwaRegister />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
